"""
bqsurvey.py — generate the BigQuery an agent runs to find and judge fields.

spec/data_requirements.yaml already holds ~330 aliases across 42 requirements:
the names each input appears under in real systems. That is a search index
nobody was using. This turns it into SQL.

The flow it supports, in order:

  01_inventory       what tables exist, how big, how fresh
  02_column_search   every alias matched against INFORMATION_SCHEMA.COLUMNS,
                     each hit tagged with the requirement it might satisfy
  03_profile         one candidate column: null rate, cardinality, range
  04_stability       the same column month by month — coverage cliffs, schema
                     changes, and the PSI baseline
  05_entity_key      is this a stable entity key or a per-session id
  06_join_rate       does this enrichment table actually cover live traffic

Steps 3-6 are where the real work is, and they are the ones usually skipped.
A field that exists and joins can still be unusable: 40% null, present only
since a migration eight months ago, or an id that turns over every session. The
fitness thresholds in spec/instance.yaml are the bar; these queries measure
against it.

Nothing here mutates anything. Every query is a SELECT, and the inventory step
runs against INFORMATION_SCHEMA rather than scanning fact tables, so the
expensive queries are the ones you choose to run per candidate column.

Run:  python bqsurvey.py [--out sql/survey]
"""
import argparse
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.abspath(__file__))

PLACEHOLDER_PROJECT = "your-project"
PLACEHOLDER_DATASETS = ["payments", "risk", "core"]


def todo(v):
    return v is None or (isinstance(v, str) and v.strip().upper() == "TODO")


def load(instance, requirements):
    with open(requirements) as f:
        reqs = yaml.safe_load(f)
    inst = {}
    if os.path.exists(instance):
        with open(instance) as f:
            inst = yaml.safe_load(f) or {}
    wh = inst.get("warehouse") or {}
    project = None if todo(wh.get("project")) else wh["project"]
    datasets = None if todo(wh.get("datasets")) else wh["datasets"]
    location = "us" if todo(wh.get("location")) else str(wh["location"]).lower()
    fitness = (inst.get("fitness") or {})
    return reqs, project, datasets, location, fitness


def header(project, datasets, filled):
    if filled:
        return (f"-- project:  {project}\n"
                f"-- datasets: {', '.join(datasets)}\n"
                f"-- Generated by bqsurvey.py from spec/instance.yaml.\n")
    return ("-- WARNING: spec/instance.yaml has warehouse.project / warehouse.datasets\n"
            "-- unfilled, so these queries carry PLACEHOLDERS. Fill the instance file and\n"
            "-- regenerate (`make survey`) rather than editing this SQL by hand — the\n"
            "-- placeholders are not a working default, they are a reminder.\n")


def alias_regex(aliases):
    """Anchored alternation over the aliases, case-insensitive, matched against
    column names. Anchoring on word-ish boundaries keeps `ip` from matching
    `zip_code` and `recipient`."""
    terms = []
    for a in aliases:
        a = a.strip()
        if not a or a.startswith("("):      # skip "(build it)" style notes
            continue
        terms.append(re.escape(a).replace(r"\ ", "[_ ]?"))
    if not terms:
        return None
    return r"(?i)(^|[^a-z0-9])(" + "|".join(terms) + r")([^a-z0-9]|$)"


def q_inventory(project, datasets, location):
    per = "\n  UNION ALL\n".join(
        f"  SELECT table_schema, table_name, creation_time, "
        f"row_count, size_bytes\n"
        f"  FROM `{project}.{d}.__TABLES__`" for d in datasets)
    return f"""\
-- 01_inventory — what exists, how big, how fresh.
-- Reads metadata only; costs nothing against the fact tables.
-- Start here: an agent that guesses table names produces confident nonsense.

WITH t AS (
{per}
)
SELECT
  table_schema,
  table_name,
  row_count,
  ROUND(size_bytes / POW(1024, 3), 2)              AS size_gb,
  TIMESTAMP_MILLIS(creation_time)                  AS created,
  -- Big and old is where facts live; small and new is usually a vendor extract.
  CASE WHEN row_count > 1e8 THEN 'fact'
       WHEN row_count > 1e6 THEN 'large'
       WHEN row_count > 0   THEN 'small'
       ELSE 'empty' END                            AS scale
FROM t
WHERE row_count > 0
ORDER BY row_count DESC;
"""


def q_column_search(reqs, project, datasets):
    rows = []
    for g in reqs["groups"]:
        for r in g["requirements"]:
            rx = alias_regex(r.get("aliases") or [])
            if not rx:
                continue
            unlocks = (len(r.get("unlocks_entities") or [])
                       + len(r.get("unlocks_measures") or [])
                       + len(r.get("unlocks_nongrid") or []))
            rows.append(
                f"    STRUCT('{r['id']}' AS req_id, '{r['criticality']}' AS criticality, "
                f"{unlocks} AS unlocks_n, r'''{rx}''' AS alias_re)")
    cols = "\n  UNION ALL\n".join(
        f"  SELECT table_schema, table_name, column_name, data_type\n"
        f"  FROM `{project}.{d}.INFORMATION_SCHEMA.COLUMNS`" for d in datasets)
    # Hoisted: an f-string expression may not contain a backslash on py3.10.
    req_block = ",\n".join(rows)
    return f"""\
-- 02_column_search — match every alias in spec/data_requirements.yaml against
-- every column name in the surveyed datasets.
--
-- This is a RECALL tool, not a decision. A hit means "worth checking"; binding
-- it requires the verify step in the requirement, plus 03-05 below. Expect
-- false positives and prefer them: a wrong hit costs one profile query, a miss
-- costs a whole feature family.
--
-- Requirements with NO hit are the finding. Those are your data gaps, and
-- `criticality = core` with zero hits blocks the search entirely.

WITH requirements AS (
  SELECT * FROM UNNEST([
{req_block}
  ])
),
cols AS (
{cols}
)
SELECT
  r.req_id,
  r.criticality,
  r.unlocks_n,                                     -- how much of the catalog this opens
  c.table_schema,
  c.table_name,
  c.column_name,
  c.data_type,
  CONCAT(c.table_schema, '.', c.table_name, '.', c.column_name) AS fq_column
FROM requirements r
LEFT JOIN cols c
  ON REGEXP_CONTAINS(c.column_name, r.alias_re)
ORDER BY
  -- unmatched core requirements first: they are the blocking findings
  CASE r.criticality WHEN 'core' THEN 0 WHEN 'high' THEN 1
                     WHEN 'medium' THEN 2 ELSE 3 END,
  c.table_name IS NOT NULL,
  r.req_id,
  c.table_schema, c.table_name, c.column_name;
"""


def q_profile(fitness):
    max_null = fitness.get("max_null_rate_pct", 5.0)
    return f"""\
-- 03_profile — is this candidate column usable at all?
-- Replace the placeholders; one run per candidate column from 02.
--
--   {{{{TABLE}}}}      fully-qualified, e.g. `proj.payments.authorization`
--   {{{{COLUMN}}}}     the candidate
--   {{{{EVENT_TS}}}}   the table's event timestamp
--   {{{{DAYS}}}}       lookback, e.g. 90
--
-- Judge against spec/instance.yaml -> fitness. A column that fails here is not
-- a weak feature, it is an unusable input, and no modelling recovers it.

SELECT
  COUNT(*)                                                   AS rows_scanned,
  COUNTIF({{{{COLUMN}}}} IS NULL)                                  AS nulls,
  ROUND(100 * COUNTIF({{{{COLUMN}}}} IS NULL) / COUNT(*), 3)       AS null_rate_pct,
  -- fitness.max_null_rate_pct = {max_null}
  IF(100 * COUNTIF({{{{COLUMN}}}} IS NULL) / COUNT(*) > {max_null},
     'FAIL null rate', 'ok')                                 AS null_verdict,

  COUNT(DISTINCT {{{{COLUMN}}}})                                   AS distinct_values,
  ROUND(COUNT(DISTINCT {{{{COLUMN}}}}) / COUNT(*), 4)              AS distinct_ratio,
  -- ~1.0 means a per-row id (useless as a group-by key);
  -- very low means a category, not an entity.

  COUNTIF(TRIM(CAST({{{{COLUMN}}}} AS STRING)) = '')               AS empty_strings,
  -- Empty string is not NULL and will silently become its own entity.

  MIN({{{{EVENT_TS}}}})                                            AS first_event,
  MAX({{{{EVENT_TS}}}})                                            AS last_event,
  MIN(IF({{{{COLUMN}}}} IS NOT NULL, {{{{EVENT_TS}}}}, NULL))            AS first_populated,
  -- If first_populated is much later than first_event, the field was added
  -- mid-history. Your usable history starts there, not at first_event.

  APPROX_QUANTILES(LENGTH(CAST({{{{COLUMN}}}} AS STRING)), 4)      AS length_quartiles
  -- Bimodal lengths usually mean two id schemes concatenated in one column.

FROM {{{{TABLE}}}}
WHERE {{{{EVENT_TS}}}} >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL {{{{DAYS}}}} DAY);
"""


def q_stability(fitness):
    swing = fitness.get("max_monthly_coverage_swing_pct", 20.0)
    months = fitness.get("min_coverage_months", 12)
    return f"""\
-- 04_stability — the check that is always skipped and always matters.
--
-- A field can be clean today and unusable for training. What you are looking
-- for: a month where null rate jumps (schema or vendor change), where distinct
-- count collapses (upstream dedupe), or where the field simply did not exist.
-- Any of those caps your usable history and invalidates a PSI baseline drawn
-- across the boundary.
--
-- Need at least {months} months of stable coverage (fitness.min_coverage_months)
-- before this field can carry a windowed feature or a PSI comparison.

WITH monthly AS (
  SELECT
    DATE_TRUNC(DATE({{{{EVENT_TS}}}}), MONTH)                      AS month,
    COUNT(*)                                                 AS rows_,
    ROUND(100 * COUNTIF({{{{COLUMN}}}} IS NULL) / COUNT(*), 3)     AS null_rate_pct,
    COUNT(DISTINCT {{{{COLUMN}}}})                                 AS distinct_values
  FROM {{{{TABLE}}}}
  WHERE {{{{EVENT_TS}}}} >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 24 MONTH)
  GROUP BY month
)
SELECT
  month,
  rows_,
  null_rate_pct,
  distinct_values,
  ROUND(null_rate_pct - LAG(null_rate_pct) OVER (ORDER BY month), 3) AS null_rate_delta,
  ROUND(SAFE_DIVIDE(distinct_values,
        LAG(distinct_values) OVER (ORDER BY month)), 3)              AS distinct_ratio_mom,
  CASE
    WHEN LAG(null_rate_pct) OVER (ORDER BY month) IS NULL THEN 'first month'
    WHEN ABS(null_rate_pct - LAG(null_rate_pct) OVER (ORDER BY month)) > {swing}
      THEN 'FAIL coverage cliff — schema or vendor change; history before this is not comparable'
    WHEN SAFE_DIVIDE(distinct_values,
         LAG(distinct_values) OVER (ORDER BY month)) < 0.5
      THEN 'FAIL cardinality collapse — upstream dedupe or id scheme change'
    ELSE 'ok'
  END                                                                AS verdict
FROM monthly
ORDER BY month;
"""


def q_entity_key(fitness):
    ratio = fitness.get("max_entity_to_session_ratio", 0.80)
    return f"""\
-- 05_entity_key — is this a stable entity key, or a per-session id wearing one?
--
-- THE most damaging mis-bind available. A session cookie bound as a device
-- fingerprint is indistinguishable in a schema browser: right name, right type,
-- fully populated. Every device-keyed feature then silently becomes worthless —
-- each device looks new, novelty features fire constantly, the entity graph has
-- no edges, and nothing errors.
--
-- Run this before building anything on any entity id.
--   {{{{ID_COLUMN}}}}       the candidate entity key
--   {{{{SESSION_COLUMN}}}}  session id, or the closest thing you have
--   {{{{ACTOR_COLUMN}}}}    customer/account id

SELECT
  COUNT(DISTINCT {{{{ID_COLUMN}}}})                                AS distinct_ids,
  COUNT(DISTINCT {{{{SESSION_COLUMN}}}})                           AS distinct_sessions,
  ROUND(SAFE_DIVIDE(COUNT(DISTINCT {{{{ID_COLUMN}}}}),
                    COUNT(DISTINCT {{{{SESSION_COLUMN}}}})), 4)    AS id_per_session,
  -- fitness.max_entity_to_session_ratio = {ratio}
  IF(SAFE_DIVIDE(COUNT(DISTINCT {{{{ID_COLUMN}}}}),
                 COUNT(DISTINCT {{{{SESSION_COLUMN}}}})) > {ratio},
     'FAIL — tracks sessions, not entities. This is a cookie. Do not bind it.',
     'ok — persists across sessions')                        AS key_verdict,

  ROUND(COUNT(*) / COUNT(DISTINCT {{{{ID_COLUMN}}}}), 2)           AS events_per_id,
  -- An entity key worth grouping on is REUSED. Near 1.0 means no history to
  -- aggregate over and every window will be empty.

  ROUND(SAFE_DIVIDE(COUNT(DISTINCT {{{{ACTOR_COLUMN}}}}),
                    COUNT(DISTINCT {{{{ID_COLUMN}}}})), 4)         AS actors_per_id
  -- >1 means the key is shared across customers, which is exactly the
  -- cross-customer reuse signal that makes it worth building on.

FROM {{{{TABLE}}}}
WHERE {{{{EVENT_TS}}}} >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY);
"""


def q_join_rate(fitness):
    min_join = fitness.get("min_join_rate_pct", 90.0)
    return f"""\
-- 06_join_rate — does this enrichment actually cover live traffic?
--
-- Enrichment tables (BIN reference, IP intelligence, email reputation, device
-- vendor) are usually stale in a specific way: they covered traffic well when
-- built and drift as new BINs, ASNs and domains appear. A table that misses
-- 20% of current traffic is not a feature, it is a feature with a 20% null rate
-- that correlates with newness — which correlates with fraud. That is worse
-- than not having it.
--
--   {{{{FACT}}}} / {{{{FACT_KEY}}}}     live traffic and its join key
--   {{{{DIM}}}}  / {{{{DIM_KEY}}}}      the enrichment table

SELECT
  COUNT(*)                                                   AS fact_rows,
  COUNTIF(d.{{{{DIM_KEY}}}} IS NOT NULL)                           AS matched,
  ROUND(100 * COUNTIF(d.{{{{DIM_KEY}}}} IS NOT NULL) / COUNT(*), 2) AS join_rate_pct,
  -- fitness.min_join_rate_pct = {min_join}
  IF(100 * COUNTIF(d.{{{{DIM_KEY}}}} IS NOT NULL) / COUNT(*) < {min_join},
     'FAIL — misses too much live traffic; the gap will correlate with novelty',
     'ok')                                                   AS join_verdict,

  ROUND(100 * COUNTIF(d.{{{{DIM_KEY}}}} IS NULL
        AND f.{{{{EVENT_TS}}}} >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY))
        / NULLIF(COUNTIF(f.{{{{EVENT_TS}}}} >= TIMESTAMP_SUB(
                 CURRENT_TIMESTAMP(), INTERVAL 7 DAY)), 0), 2) AS recent_miss_rate_pct
  -- Compare against the overall miss rate. Rising = the table is going stale.

FROM {{{{FACT}}}} f
LEFT JOIN {{{{DIM}}}} d
  ON f.{{{{FACT_KEY}}}} = d.{{{{DIM_KEY}}}}
WHERE f.{{{{EVENT_TS}}}} >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY);
"""


def build(out="sql/survey", instance=None, requirements=None):
    instance = instance or os.path.join(ROOT, "spec", "instance.yaml")
    requirements = requirements or os.path.join(ROOT, "spec", "data_requirements.yaml")
    reqs, project, datasets, location, fitness = load(instance, requirements)

    filled = bool(project and datasets)
    project = project or PLACEHOLDER_PROJECT
    datasets = datasets or PLACEHOLDER_DATASETS

    outdir = os.path.join(ROOT, out)
    os.makedirs(outdir, exist_ok=True)

    files = {
        "01_inventory.sql": q_inventory(project, datasets, location),
        "02_column_search.sql": q_column_search(reqs, project, datasets),
        "03_profile.sql": q_profile(fitness),
        "04_stability.sql": q_stability(fitness),
        "05_entity_key.sql": q_entity_key(fitness),
        "06_join_rate.sql": q_join_rate(fitness),
    }
    head = header(project, datasets, filled)
    for name, body in files.items():
        with open(os.path.join(outdir, name), "w") as f:
            f.write(head + "\n" + body)

    n_alias = sum(len(r.get("aliases") or []) for g in reqs["groups"] for r in g["requirements"])
    print(f"wrote {outdir}/ — {len(files)} queries, "
          f"{n_alias} aliases across {sum(len(g['requirements']) for g in reqs['groups'])} "
          f"requirements")
    if not filled:
        print("  NOTE: warehouse.project / warehouse.datasets are TODO in "
              "spec/instance.yaml — queries carry placeholders.", file=sys.stderr)
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate the BigQuery discovery survey.")
    ap.add_argument("--out", default="sql/survey")
    ap.add_argument("--instance")
    ap.add_argument("--requirements")
    a = ap.parse_args(argv)
    return build(out=a.out, instance=a.instance, requirements=a.requirements)


if __name__ == "__main__":
    sys.exit(main())
