"""
nongrid_features.py — the families the slot grammar cannot express.

Columns: (family, feature_name, definition, inputs_required, typologies,
          availability, leakage_risk, adversarial_halflife)

typologies use the ids from feature_space.yaml:
  stolen_cnp | ato | card_test | synthetic | mule | friendly | refund_abuse

This list is the agent's STARTING point for these families, not the finished set.
Section 4 of AGENT_BRIEF.md sets a minimum count per family; exceeding it is expected.
"""

RT, ENR, STR, BATCH = "realtime", "enrichment", "streaming", "batch_only"
LOW, MED, HIGH = "LOW", "MED", "HIGH"
D, W, M = "days-weeks", "weeks-months", "months-quarters"

NONGRID = [
# ── GRAPH ────────────────────────────────────────────────────────────────────
("graph","graph_degree_pan_1hop","Count of distinct entities linked to this card at 1 hop","entity graph","stolen_cnp,card_test",STR,LOW,M),
("graph","graph_degree_device_1hop","Distinct entities linked to this device at 1 hop","entity graph","card_test,mule",STR,LOW,W),
("graph","graph_component_size_2hop","Size of the connected component containing this txn at 2 hops","entity graph","mule,synthetic",STR,LOW,M),
("graph","graph_component_cb_rate_pit","Point-in-time CB rate of the component, labels filtered on arrival ts","entity graph + labels","stolen_cnp,mule",STR,HIGH,M),
("graph","graph_confirmed_fraud_1hop","Count of confirmed-fraud nodes within 1 hop","entity graph + labels","stolen_cnp,mule",STR,HIGH,M),
("graph","graph_confirmed_fraud_2hop","Count of confirmed-fraud nodes within 2 hops","entity graph + labels","mule,synthetic",STR,HIGH,M),
("graph","graph_dist_to_nearest_fraud","Shortest-path hops to nearest confirmed-fraud node","entity graph + labels","mule,synthetic",STR,HIGH,M),
("graph","graph_component_density","Edges/nodes ratio of the component (rings are dense)","entity graph","mule,card_test",STR,LOW,M),
("graph","graph_component_growth_24h","Node count added to the component in last 24h","entity graph","card_test,mule",STR,LOW,W),
("graph","graph_component_age_days","Days since the component's earliest node first seen","entity graph","synthetic",STR,LOW,M),
("graph","graph_pagerank","PageRank centrality of the primary entity node","entity graph","mule",BATCH,LOW,M),
("graph","graph_bridge_score","Whether this txn's entity bridges two previously disjoint components","entity graph","mule,synthetic",STR,LOW,M),
("graph","graph_recv_fanin_1hop","Distinct senders linked to this receiver at 1 hop","entity graph","mule",STR,LOW,M),
("graph","graph_shared_addr_distinct_names","Distinct names at this normalized address","address normalization","synthetic,mule",STR,LOW,M),
# ── NOVELTY / AGE ────────────────────────────────────────────────────────────
("novelty","age_days_cust","Days since customer first seen","first_seen table","friendly,synthetic",RT,LOW,W),
("novelty","age_days_pan","Days since card first seen on platform","first_seen table","stolen_cnp",RT,LOW,M),
("novelty","age_days_device","Days since device first seen","first_seen table","ato,card_test",RT,LOW,W),
("novelty","age_days_email","Days since email first seen on platform","first_seen table","synthetic",RT,LOW,D),
("novelty","age_days_email_external","Email age from enrichment vendor (first seen in the wild)","email intel vendor","synthetic",ENR,LOW,W),
("novelty","age_days_addr_ship","Days since ship/payout address first seen","first_seen table","mule",RT,LOW,M),
("novelty","age_days_receiver","Days since receiver first seen","first_seen table","mule",RT,LOW,M),
("novelty","is_first_txn_cust","First-ever transaction for this customer","first_seen table","stolen_cnp,synthetic",RT,LOW,W),
("novelty","is_new_device_for_cust","Device never before seen for this customer","cust-device history","ato",RT,LOW,W),
("novelty","is_new_pan_for_cust","Card never before seen for this customer","cust-pan history","ato,stolen_cnp",RT,LOW,M),
("novelty","is_new_country_for_cust","Country never before seen for this customer","cust-geo history","ato",RT,LOW,W),
("novelty","is_new_receiver_for_cust","Payout destination never used before by this customer","cust-recv history","ato,mule",RT,LOW,M),
("novelty","novelty_combo_newdev_oldpan","New device AND card age > 180d (ATO signature)","first_seen table","ato",RT,LOW,W),
("novelty","novelty_combo_agedemail_newall","Email age > 365d but device/addr/pan all new (synthetic signature)","first_seen + email intel","synthetic",ENR,LOW,W),
("novelty","age_pctile_cust_in_pop","Customer age percentile among active population (controls portfolio growth)","first_seen table","friendly",RT,LOW,M),
("novelty","dormancy_days_then_burst","Days dormant immediately preceding a >3x volume spike","txn history","ato",RT,LOW,W),
# ── DEVIATION FROM CUSTOMER BASELINE ─────────────────────────────────────────
("deviation","dev_amt_z_vs_cust","Amount z-score against customer's own trailing amount distribution","cust txn history","ato,friendly",RT,LOW,W),
("deviation","dev_amt_pctile_vs_cust","Amount percentile within customer's own history","cust txn history","ato",RT,LOW,W),
("deviation","dev_amt_max_ratio","Amount / customer's historical max amount","cust txn history","ato",RT,LOW,W),
("deviation","dev_is_new_mcc_for_cust","MCC never used by this customer before","cust txn history","ato",RT,LOW,W),
("deviation","dev_mcc_prob_given_cust","Empirical P(MCC | customer history), smoothed","cust txn history","ato",RT,LOW,W),
("deviation","dev_hour_prob_given_cust","P(hour-of-day | customer history), smoothed","cust txn history","ato",RT,LOW,W),
("deviation","dev_geo_km_from_modal","Km from customer's modal transaction geohash","cust geo history","ato,stolen_cnp",RT,LOW,W),
("deviation","dev_geo_km_from_last","Km from customer's previous transaction location","cust geo history","ato",RT,LOW,W),
("deviation","dev_interarrival_z","Inter-arrival time z-score vs customer's own cadence","cust txn history","card_test,ato",RT,LOW,D),
("deviation","dev_device_switch_flag","Device differs from customer's modal device","cust device history","ato",RT,LOW,W),
("deviation","dev_currency_new_flag","Currency never used by this customer","cust txn history","ato,mule",RT,LOW,W),
("deviation","dev_velocity_ratio_vs_own_30d","Today's txn count / customer's own 30d daily mean","cust txn history","ato,card_test",RT,LOW,D),
("deviation","dev_basket_z_vs_cust","Basket size z-score vs customer's own history","order history","friendly,refund_abuse",RT,LOW,M),
# ── CROSS-FIELD CONSISTENCY ──────────────────────────────────────────────────
("consistency","cons_bin_ctry_eq_ip_ctry","BIN country == IP country","BIN table + IP geo","stolen_cnp",ENR,LOW,D),
("consistency","cons_bin_ctry_eq_bill_ctry","BIN country == billing country","BIN table","stolen_cnp",ENR,LOW,M),
("consistency","cons_bill_ctry_eq_ship_ctry","Billing country == ship/receiver country","txn fields","stolen_cnp,mule",RT,LOW,M),
("consistency","cons_ip_ctry_eq_bill_ctry","IP country == billing country","IP geo","stolen_cnp",ENR,LOW,D),
("consistency","cons_doc_ctry_eq_birth_ctry","Document-issuing country == birth country","KYC fields","synthetic",RT,LOW,M),
("consistency","cons_phone_cc_eq_bill_ctry","Phone country code == billing country","phone parse","synthetic",RT,LOW,D),
("consistency","cons_device_locale_eq_bill_ctry","Device locale country == billing country","device fp","stolen_cnp",RT,LOW,D),
("consistency","cons_device_tz_minus_ip_tz","Device timezone offset - IP timezone offset (minutes)","device fp + IP geo","stolen_cnp",ENR,LOW,D),
("consistency","cons_count_geo_mismatches","Count of pairwise country mismatches across all geo-bearing fields","all geo fields","stolen_cnp,mule",ENR,LOW,D),
("consistency","cons_km_bill_to_ship","Haversine km, billing to ship/payout address","geocoding","stolen_cnp,mule",ENR,LOW,M),
("consistency","cons_km_ip_to_bill","Haversine km, IP to billing address","geocoding + IP geo","stolen_cnp",ENR,LOW,D),
("consistency","cons_impossible_travel_kmh","Implied km/h between consecutive txns on same card","txn history + geo","stolen_cnp,ato",STR,LOW,D),
("consistency","cons_name_jw_card_vs_acct","Jaro-Winkler, cardholder name vs account name","name fields","stolen_cnp",RT,LOW,M),
("consistency","cons_name_jw_acct_vs_doc","Jaro-Winkler, account name vs KYC document name","KYC fields","synthetic",RT,LOW,M),
("consistency","cons_name_in_email_local","Account surname appears in email local-part","email + name","synthetic",RT,LOW,D),
("consistency","cons_dob_age_years","Age implied by DOB (tails are risky both ways)","KYC fields","synthetic",RT,LOW,M),
("consistency","cons_dob_doc_expiry_gap","Document expiry minus today, days","KYC fields","synthetic",RT,LOW,M),
("consistency","cons_recv_ctry_in_highrisk_list","Receiver country on sanctions/high-risk corridor list","reference list","mule",RT,LOW,M),
# ── IDENTIFIER STRINGS / ENTROPY ─────────────────────────────────────────────
("strings","str_email_local_len","Email local-part length","email","synthetic,card_test",RT,LOW,D),
("strings","str_email_digit_ratio","Digit characters / total in local-part","email","synthetic",RT,LOW,D),
("strings","str_email_max_digit_run","Longest consecutive digit run in local-part","email","synthetic",RT,LOW,D),
("strings","str_email_char_entropy","Shannon entropy of local-part characters","email","synthetic",RT,LOW,D),
("strings","str_email_dict_word_ratio","Share of local-part decomposable into dictionary words","email + wordlist","synthetic",RT,LOW,D),
("strings","str_email_keyboard_walk","Local-part contains a keyboard-adjacency run","email","card_test",RT,LOW,D),
("strings","str_email_has_plus_tag","Plus-tagging present","email","refund_abuse",RT,LOW,D),
("strings","str_email_canon_collisions","Count of distinct raw emails collapsing to this canonical form","email history","refund_abuse,synthetic",STR,LOW,D),
("strings","str_email_min_edit_dist_pop","Min Levenshtein distance to any email seen in last 7d","email history","card_test,synthetic",STR,LOW,D),
("strings","str_email_dom_is_disposable","Domain on disposable-provider list","reference list","synthetic,refund_abuse",ENR,LOW,D),
("strings","str_email_dom_class","free / corporate / disposable / edu / custom","reference list","synthetic",ENR,LOW,D),
("strings","str_email_dom_age_days","Domain registration age","WHOIS enrichment","synthetic",ENR,LOW,W),
("strings","str_email_mx_valid","MX record resolves","DNS enrichment","synthetic",ENR,LOW,D),
("strings","str_addr2_has_unit_cycling","Same addr line 1 with many distinct line 2 values","address history","mule",STR,LOW,M),
("strings","str_name_is_random_like","Name fails first/surname frequency plausibility check","name freq tables","synthetic",RT,LOW,M),
# ── SESSION / SEQUENCE ───────────────────────────────────────────────────────
("sequence","seq_secs_signup_to_first_txn","Seconds from account creation to first transaction","account events","synthetic,stolen_cnp",RT,LOW,W),
("sequence","seq_secs_cardadd_to_use","Seconds from card added to card used","account events","stolen_cnp,ato",RT,LOW,W),
("sequence","seq_secs_login_to_checkout","Seconds from login to checkout submit","session events","ato,card_test",RT,LOW,D),
("sequence","seq_pwd_changes_24h","Password changes in last 24h","account events","ato",STR,LOW,W),
("sequence","seq_email_changes_7d","Email changes in last 7d","account events","ato",STR,LOW,W),
("sequence","seq_phone_changes_7d","Phone changes in last 7d","account events","ato",STR,LOW,W),
("sequence","seq_payout_dest_changes_7d","Payout destination changes in last 7d","account events","ato,mule",STR,LOW,M),
("sequence","seq_failed_logins_24h","Failed login attempts in last 24h","auth logs","ato",STR,LOW,D),
("sequence","seq_declines_this_session","Prior declines within this session","session events","card_test",RT,LOW,D),
("sequence","seq_distinct_bins_this_session","Distinct BINs entered this session","session events","card_test",RT,LOW,D),
("sequence","seq_card_field_edits","Card-number field edit/correction count","client telemetry","card_test",RT,LOW,D),
("sequence","seq_ship_addr_changed_post_cart","Ship address edited after cart creation","session events","stolen_cnp",RT,LOW,W),
("sequence","seq_nav_path_len","Page count before checkout","session events","stolen_cnp,card_test",RT,LOW,D),
("sequence","seq_direct_to_checkout","Session entered directly at checkout URL","session events","card_test",RT,LOW,D),
("sequence","seq_acquisition_channel","Acquisition channel / campaign / affiliate id","attribution","synthetic,refund_abuse",RT,MED,W),
("sequence","seq_affiliate_cb_rate_pit","Point-in-time CB rate of the acquiring affiliate","attribution + labels","synthetic",STR,HIGH,M),
("sequence","seq_time_since_last_support_contact","Days since last customer-support contact","CS system","friendly,refund_abuse",BATCH,LOW,M),
("sequence","seq_prior_dispute_count","Prior disputes filed by this customer","dispute history","friendly,refund_abuse",STR,HIGH,M),
# ── CLIENT TELEMETRY / BEHAVIORAL BIOMETRICS ─────────────────────────────────
("biometrics","bio_pan_entry_pasted","Card number pasted rather than typed","client telemetry","stolen_cnp,card_test",RT,LOW,D),
("biometrics","bio_pan_entry_autofilled","Card number autofilled by browser","client telemetry","stolen_cnp",RT,LOW,D),
("biometrics","bio_typing_cadence_cv","Coefficient of variation of inter-keystroke intervals","client telemetry","card_test",RT,LOW,D),
("biometrics","bio_form_fill_seconds","Total checkout form completion time","client telemetry","card_test",RT,LOW,D),
("biometrics","bio_backspace_count","Corrections during form entry","client telemetry","stolen_cnp",RT,LOW,D),
("biometrics","bio_mouse_entropy","Entropy of mouse movement path","client telemetry","card_test",RT,LOW,D),
("biometrics","bio_focus_loss_events","Tab-away events during checkout (reading stolen data)","client telemetry","stolen_cnp",RT,LOW,D),
("biometrics","bio_is_headless","Headless-browser signature detected","client telemetry","card_test",RT,LOW,D),
("biometrics","bio_is_emulator","Mobile emulator signature detected","client telemetry","card_test",RT,LOW,D),
("biometrics","bio_automation_flags","WebDriver / automation property count","client telemetry","card_test",RT,LOW,D),
("biometrics","bio_hw_concurrency_mismatch","Reported CPU cores inconsistent with claimed device model","client telemetry","card_test",RT,LOW,D),
("biometrics","bio_screen_res_rare","Screen resolution rarity percentile in population","client telemetry","card_test",RT,LOW,D),
("biometrics","bio_ip_is_datacenter","IP classified datacenter/hosting","IP intel vendor","card_test,mule",ENR,LOW,D),
("biometrics","bio_ip_is_vpn_proxy_tor","IP classified VPN / proxy / Tor","IP intel vendor","stolen_cnp,card_test",ENR,LOW,D),
("biometrics","bio_asn_abuse_score","Vendor abuse score for the ASN","IP intel vendor","card_test",ENR,MED,W),
# ── INSTRUMENT / AUTHORIZATION ───────────────────────────────────────────────
("instrument","inst_avs_response","AVS response code (grouped)","auth response","stolen_cnp",RT,LOW,M),
("instrument","inst_cvv_response","CVV/CVC match result","auth response","stolen_cnp",RT,LOW,M),
("instrument","inst_3ds_attempted","3DS attempted flag","auth flow","stolen_cnp",RT,LOW,M),
("instrument","inst_3ds_auth_status","3DS authentication outcome","auth flow","stolen_cnp,friendly",RT,LOW,M),
("instrument","inst_liability_shift","Liability shifted to issuer","auth flow","friendly",RT,LOW,M),
("instrument","inst_is_network_token","Network token vs raw PAN","auth flow","stolen_cnp",RT,LOW,M),
("instrument","inst_funding_type","credit / debit / prepaid / deferred-debit","BIN table","stolen_cnp,synthetic",ENR,LOW,M),
("instrument","inst_is_commercial","Commercial vs consumer card","BIN table","mule",ENR,LOW,M),
("instrument","inst_issuer_country_tier","Issuer country risk tier","BIN table + reference","stolen_cnp",ENR,LOW,M),
("instrument","inst_issuer_size_decile","Issuer portfolio-size decile (small issuers detect slower)","BIN table","stolen_cnp",ENR,LOW,M),
("instrument","inst_days_to_card_expiry","Days until card expiry","card fields","stolen_cnp",RT,LOW,M),
("instrument","inst_expiry_retry_variants","Distinct expiry values tried for the same PAN","auth history","card_test",STR,LOW,D),
("instrument","inst_bin_reissue_recent","BIN range recently reissued by issuer","BIN table","stolen_cnp",ENR,LOW,M),
# ── BASKET / FULFILLMENT ─────────────────────────────────────────────────────
("basket","bskt_resale_liquidity_score","Category-level resale liquidity index","product catalog","stolen_cnp",BATCH,LOW,M),
("basket","bskt_is_digital","Digital vs physical goods","product catalog","stolen_cnp,friendly",RT,LOW,M),
("basket","bskt_expedited_shipping","Expedited shipping selected","order fields","stolen_cnp",RT,LOW,M),
("basket","bskt_ship_cost_pct","Shipping cost as % of order value","order fields","stolen_cnp",RT,LOW,M),
("basket","bskt_max_identical_sku_qty","Max quantity of a single SKU","order fields","stolen_cnp,refund_abuse",RT,LOW,M),
("basket","bskt_has_gift_message","Gift message present","order fields","stolen_cnp",RT,LOW,M),
("basket","bskt_addr_type","residential / commercial / PO box / freight forwarder","address enrichment","stolen_cnp,mule",ENR,LOW,M),
("basket","bskt_is_reshipper_match","Ship address on known reshipper list","reference list","stolen_cnp",ENR,LOW,M),
("basket","bskt_pickup_in_store","BOPIS flag","order fields","stolen_cnp",RT,LOW,M),
("basket","bskt_delivery_confirmed","Carrier delivery confirmation received (POST-txn: later-lifecycle models only)","logistics feed","friendly",BATCH,MED,M),
("basket","bskt_delivery_days_actual","Actual days to delivery (POST-txn)","logistics feed","friendly",BATCH,MED,M),
("basket","bskt_prior_refund_rate_cust","Point-in-time refund rate for this customer","refund history","refund_abuse,friendly",STR,HIGH,M),
("basket","bskt_amount_vs_category_p95","Order amount vs category 95th percentile","product catalog","stolen_cnp",BATCH,LOW,M),
# ── POPULATION CONTEXT / REGIME ──────────────────────────────────────────────
("population","pop_portfolio_cb_rate_pit","Portfolio CB rate for the trailing window, point-in-time","labels","stolen_cnp",STR,HIGH,M),
("population","pop_hourly_txn_volume_z","Current hourly volume z-score vs same hour-of-week baseline","txn stream","card_test",STR,LOW,W),
("population","pop_hourly_decline_rate_z","Current hourly decline rate z-score","txn stream","card_test",STR,LOW,W),
("population","pop_champ_score_mean_1h","Population mean champion score, last hour (attack-wave detector)","score stream","card_test",STR,MED,W),
("population","pop_segment_share_shift","Segment mix PSI vs trailing 30d","txn stream","card_test",STR,LOW,M),
("population","pop_is_promo_window","Active promotion / flash sale flag","marketing calendar","refund_abuse",RT,LOW,M),
("population","pop_is_holiday_peak","Holiday peak-season flag","calendar","friendly",RT,LOW,M),
("population","pop_rule_release_recency","Days since last upstream rule change (denominator shifts)","change log","stolen_cnp",BATCH,MED,M),
]
